"""Access to the bundled example structures.

These files are **synthetic**, not real proteins. They exist so that
``pocketscribe demo`` and the whole test suite run offline with no external downloads,
and so that tests can assert against geometry that is known in advance rather than
against whatever the tool happened to produce.

They are generated by ``scripts/make_example_structures.py``, which is checked into the
repository: nothing here is hand-edited, and the provenance of every bundled file is
auditable.
"""

from __future__ import annotations

from pathlib import Path

from ..errors import InputStructureError

EXAMPLE_DIR = Path(__file__).parent / "example_structures"

#: The single-structure demo: an AlphaFold2-style model of synthetic protein 1.
DEMO_STRUCTURE = ("AF-SYNTH01-F1-model_v4.pdb", "alphafold2")

#: The consensus demo. Two MSA-based models plus one single-sequence model, so the
#: report shows cross-family and same-family agreement side by side -- which is the
#: whole point of the stage.
DEMO_CONSENSUS = [
    ("AF-SYNTH01-F1-model_v4.pdb", "alphafold2"),
    ("synth01_openfold_model_1.pdb", "openfold"),
    ("synth01_esmfold.pdb", "esmfold"),
]

#: A different protein, used to check that consensus refuses mismatched inputs.
DIFFERENT_PROTEIN = ("AF-SYNTH02-F1-model_v4.pdb", "alphafold2")

#: A crystallographic-style file whose B-factors are per-atom temperature factors.
EXPERIMENTAL_LIKE = "experimental_like.pdb"

#: The Tier 2 reference adapter's example, with its confidence sidecar.
BOLTZ_STRUCTURE = ("boltz_synth01_model_0.pdb", "boltz")


def example_path(name: str) -> Path:
    """Resolve a bundled example by filename."""
    path = EXAMPLE_DIR / name
    if not path.is_file():
        raise InputStructureError(
            f"Bundled example structure '{name}' is missing from {EXAMPLE_DIR}. "
            "Regenerate the examples with: python scripts/make_example_structures.py"
        )
    return path


def demo_structure() -> tuple[Path, str]:
    """Path and source id for the single-structure demo."""
    name, source_id = DEMO_STRUCTURE
    return example_path(name), source_id


def demo_consensus_structures() -> list[tuple[Path, str]]:
    """Paths and source ids for the cross-model consensus demo."""
    return [(example_path(name), source_id) for name, source_id in DEMO_CONSENSUS]


def different_protein() -> tuple[Path, str]:
    """A structure of a different protein, for the mismatch-rejection path."""
    name, source_id = DIFFERENT_PROTEIN
    return example_path(name), source_id
